name: Bot

on:
  issues:
    types: [opened, edited, labeled]
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  bot:
    name: ${{ github.event_name }}/${{ github.event.action }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: familyjs/bot@main
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
        env:
          GIT_AUTHOR_NAME: Famibot
          GIT_AUTHOR_EMAIL: famibot08@gmail.com
          GIT_COMMITTER_NAME: Famibot
          GIT_COMMITTER_EMAIL: famibot08@gmail.com
