name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      plugins: ${{ steps.packages.outputs.paths }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@ce177499ccf9fd2aded3b0426c97e5434c2e8a73
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Latest
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: NPM ^9.5.0
        run: npm i -g npm@^9.5.0 --registry=https://registry.npmjs.org
      - uses: actions/checkout@v3
      - name: Restore Dependency Cache
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */node_modules
          key: dependency-cache-${{ hashFiles('package.json', '*/package.json') }}
      - run: npm install
      - id: files
        uses: imhoffd/get-changed-files@v2
        with:
          format: 'json'
      - id: packages
        uses: ./.github/actions/changed-packages
        with:
          files: ${{ steps.files.outputs.all }}
  lint:
    runs-on: macos-12
    timeout-minutes: 30
    needs:
      - setup
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: NPM ^9.5.0
        run: npm i -g npm@^9.5.0 --registry=https://registry.npmjs.org
      - uses: actions/checkout@v3
      - name: Restore Dependency Cache
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */node_modules
          key: dependency-cache-${{ hashFiles('package.json', '*/package.json') }}
      - run: npm install
      - run: npm run lint
