name: Publish Latest

on: workflow_dispatch

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  publish-npm-latest:
    uses: ./.github/workflows/publish-npm-latest.yml
    secrets:
      JIG_GH_RELEASE_TOKEN: ${{ secrets.JIG_GH_RELEASE_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
