name: Publish NPM Weekly

on:
  schedule:
    - cron: "0 23 * * sun"

permissions:
  contents: write
  id-token: write

jobs:
  deploy-npm-weekly:
    if: github.ref == 'refs/heads/main'
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.JIG_GH_RELEASE_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: npm
          cache-dependency-path: '**/package.json'
      - run: |
          npm install
      - name: Version & Publish
        env:
          GH_TOKEN: ${{ secrets.JIG_GH_RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "Github Workflow (on behalf of ${{ github.actor }})"
          git config user.email "users.noreply.github.com"
          npm whoami
          npm run ci:publish:weekly
